### ISSUE TITLE
Always unclickable

### ISSUE THREAD

**Issue by chongxi** [n1k0/SublimeHighlight#40]
I click [Edit] -> [Highlight] -> [...]
And all those command such as "copy to clipboard as rtf" is grey, I am not allowed to click. Could you please tell me why is that?

**Comment by Ewarren7** [comment]
I seem to be having the same problem. I installed via package control after adding repo https://github.com/n1k0/SublimeHighlight/tree/python3. I also quit and restarted sublime. 

Sublime Text 2 v 2.0.2 build 2221on OS x 10.10.1 (Yosemite)

I also uninstalled via PC and Reinstalled. Same problem. 

![image](https://cloud.githubusercontent.com/assets/7004081/5663163/42a241b4-9711-11e4-8c56-d5b21808e7e9.png)

**Comment by Blackbaud-GuillaumeUys** [comment]
Hello, I am also experiencing the same problem, menu items grayed out. I followed the instructions on github and mentioned her. Windows 7 Enterprise SP1, Sublime Text Build 3065. None of the plugin files shown in the menu (README, user settings or default settings) show any content.

**Comment by afilina** [comment]
In case someone here uses Sublime Text 2 and the menu is greyed out, try this:
- Remove the package, remove the repo.
- Add the repo https://github.com/n1k0/SublimeHighlight instead of the one mentioned in the README.
- Install the package SublimeHighlight.
- Restart Sublime.

The repo https://github.com/n1k0/SublimeHighlight/tree/python3 is for Sublime Text 3 users, not 2.

**Comment by carlosbutler** [comment]
@afilina solution worked for me. However, when looking for the package it appears as **Highlight** and not **SublimeHighlight**, in my case anyway.

**Comment by JakePeyser** [comment]
Thanks @afilina - solved my issue. Didn't even consider that as adding the wrong repo...

Great package @n1k0  - very useful when I'm taking notes with code that can use a little syntax flavor

**Comment by mboeckle** [comment]
@afilina great thank you!

**Comment by alexkaskasoli** [comment]
I'm using Sublime Text 3 Build 3065 on Fedora Linux. I have the greyed out issue as well.

I installed using Package Control and https://github.com/n1k0/SublimeHighlight/tree/python3 repo.

Installed the SFTP plugin from Package Control and it works fine. Tried re-installed SublimeHighlight a couple of times, same issue.

n1k0 if you want any more info about the issue just give me a shout.

**Comment by solstice333** [comment]
@afilina Thanks for the add repo tip! Worked great.

**Comment by caroksh** [comment]
Hi. I have the same issue but the strange thing is that when I installed it at first it was working OK for a couple of days and then suddenly the Highlight options in the menu are greyed out (can't use them).
I've tried all what has been said here but nothing changes.
I hope someone finds a solution for this issue because it's a great pluggin, very useful for me. Thanks n1k0.

**Comment by tyiannak** [comment]
Any updates on that? I've just installed it on Ubuntu, Sublime 3, using the https://github.com/n1k0/SublimeHighlight/tree/python3 repo and all sublimehighlight menus are greyed.
